name: Trigger Workflow in Destination Repo

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger starter theme update in destination repo
        run: |
          curl -X POST https://api.github.com/repos/rareview/wpe-starter/dispatches \
          -H "Authorization: token ${{ secrets.WPE_STARTER_ACCESS }}" \
          -d '{"event_type": "remote-update-trigger", "client_payload": {"ref": "refs/heads/master"}}'
